-- Reliable local hit sound for the current LvkHub practice adapter.
-- IMPORTANT: this module NEVER watches Humanoid.Health globally.
-- It only plays when the local weapon/practice adapter explicitly calls
-- shared.LvkHubPlayHitSound after a hit generated by THIS client.
return function(State, Registry, UI)
    local Workspace=game:GetService("Workspace")

    local function removeLegacySounds(parent)
        if not parent then return end
        for _,name in ipairs({
            "LvkHubHitSoundV2",
            "LvkHubHitSoundV3",
            "LvkHubHitSoundV4",
            "LvkHubDummyHitSoundV2",
            "LvkHubConfirmedHitSound",
        }) do
            local old=parent:FindFirstChild(name)
            if old then pcall(function() old:Destroy() end) end
        end
    end

    removeLegacySounds(Workspace.CurrentCamera)
    removeLegacySounds(Workspace)

    local sound=Instance.new("Sound")
    sound.Name="LvkHubDummyHitSoundV2"
    sound.SoundId="rbxassetid://91546829095879"
    sound.Volume=.85
    sound.Parent=Workspace.CurrentCamera or Workspace

    Workspace:GetPropertyChangedSignal("CurrentCamera"):Connect(function()
        local cam=Workspace.CurrentCamera
        if not cam then return end
        removeLegacySounds(cam)
        sound.Parent=cam
    end)

    local lastPlay=0

    local function play()
        if not State.Local.HitSound then return end

        local now=os.clock()
        -- Prevent duplicate callbacks for one locally-produced hit.
        if now-lastPlay<.055 then return end
        lastPlay=now

        local cam=Workspace.CurrentCamera
        if cam and sound.Parent~=cam then sound.Parent=cam end

        pcall(function()
            sound:Stop()
            sound.TimePosition=0
            sound:Play()
        end)
    end

    -- Single playback entry point.
    -- WeaponSystemDummyAdapter / local confirmed-hit code may call this after
    -- determining that the hit belongs to LocalPlayer's shot.
    shared.LvkHubPlayHitSound=play

    -- Deliberately NO Humanoid.Health polling here.
    -- A health decrease can be caused by another player, fall damage, melee,
    -- server effects, etc.; using it as a hit source caused false hit sounds.
end
